### ISSUE TITLE
Making Twirp::Error a descendant of StandardError

### ISSUE THREAD

**Issue by gaffneyc** [twitchtv/twirp-ruby#36]
I was working on a client today and had the natural inclination to raise the response error for any of the cases we weren't sure how to handle yet. Unfortunately that doesn't work very well since Twirp::Error is just an Object and can't be raised.

Would you be open to a PR to refactor Twirp::Error to be a child of StandardError so it could be raised?

**Comment by marioizquierdo** [comment]
I'm not sure it would be a good idea, because conceptually they are different things. The Twirp client raises exceptions if there are issues with the connection, but not on Twirp errors because they are just "data". For example, `not_found` or `invalid_argument` errors could be used to trigger business logic.

I understand this may not apply to your case, maybe your Twirp service is designed in a way that `not_found` should never happen, therefore it is easier for you to just handle any error whatsoever as an Exception. But I'm not sure we can generalize this to everybody.

If you want to handle logic errors as `StandardError` exceptions, you could make a wrapper class, or a wrapper method like this:

```ruby
# Convert a Twirp::Error to a StandardError so it can be raised.
# If the error is an internal error with a cause, it is unwrapped to keep the original stacktrace
def standard_error_from_twirp_error(twerr)
  if twerr.cause.is_a? StandardError
    twerr.cause
  else
    StandardError.new(twerr.to_s)
  end
end
```

Then you can use it like this:

```ruby
resp = myservice.mymethod(foo: "bar")
raise standard_error_from_twirp_error(resp.error) if resp.error
```

I could consider implementing this in the `Twirp::Error` as a method, so you can do `twerr.to_exception` instead. That seems less intrusive than inheritance. Would that work for you? Or were you thinking about a different way to raise errors?

**Comment by marioizquierdo** [comment]
Would the recommendation on the previous comment work for you? Or were you thinking about something different?

If this works, we could add a method `to_exception` on `Twirp::Error` to do the same thing. That seems less intrusive than doing inheritance.

With the `to_exception` method, you code would look like this instead:

```ruby
resp = myservice.mymethod(foo: "bar")
raise resp.error.to_exception if resp.error
```

**Comment by gaffneyc** [comment]
Yeah, the rationale makes sense about them being values and not exceptions per se. My original thought was to convert them to Errors so they could be raised (with an error hierarchy) but continue to treat them as values or add methods that would raise errors similar to ActiveRecord or other client libraries. It is, for me at least, trying to get the ergonomics to feel more like standard Ruby than Go.

A more fleshed out example of the end state that is in my head is below. Again, I'm not sure if it's an improvement so feel free to close the ticket if you don't think it's a good fit or direction for Twirp. We can use a version of your first comment locally to at least get what we're looking for.
```ruby
module Twirp
  # Error has the same API and methods as today
  class Error < StandardError
    ...
  end

  class NotFound < Error; end
  class InvalidArgument < Error; end
end
```

```ruby
class SnitchesController < ApplicationController
  rescue_from Twirp::NotFound, with: :not_found
  rescue_from Twirp::PermissionDenied, with: :not_authorized

  def get
    begin
      # get_snitch! could be generated or monkey patched in
      resp = @client.get_snitch!(token: "c2354d53d2")
    rescue Twirp::NotFound
      render status: 404
    rescue Twirp::Error => e
      render status: 500, text: e.message
    end
  end
end
```

**Comment by marioizquierdo** [comment]
I see what you mean.

That would work, but it would also add alternative ways to do the same thing, which I know is part of Ruby's culture, but I still try to avoid when possible.

Having `Twirp::Error <StandardError` would simplify this, but I still don't think it is a good idea, because the service needs to return errors as values (specially for 4xx-type errors), without having to worry about stacktraces, performance, etc. Twirp values the simplicity of returning data in the service and getting the same data in the client.

I like the exclamation-mark methods, they are easy to implement, but they also add some complexity to the mix.

Maybe a reasonable middle-ground is to implement the type `Twirp::Exception < StandardError`, and the `error.to_exception` method. Without all the other error types for each code. Keeps the implementation simple, and allows to easily monkey-patch the exclamation-mark methods if that works better in some cases.

```ruby
module Twirp
  # Same as before. Error represents data and is not an Exception
  class Error
    # ...

    def to_exception
      # returns Twirp::Exception that can be raised and rescued
    end
  end

  class Exception < StandardError
    # ... has same methods as Error, but it is also an exception
  end
end
```

It would be used with a single handler, but that has access to the error `code`, `msg` and `meta`, in addition to the exception `message`, `backtrace`, etc.

```
class SnitchesController < ApplicationController
  rescue_from Twirp::Exception, with: :handle_twirp_exception

  def get
      resp = @client.get_snitch(token: "c2354d53d2")
      raise resp.to_exception if resp.error
    rescue Twirp::NotFound
      render status: 404
    rescue Twirp::Error => e
      render status: 500, text: e.message
    end
  end

private

  def handle_twirp_exception(exception)
    case exception.code
    when :not_found
      render status: 404
    else
      render status: 404
    end
  end
end
```

**Comment by marioizquierdo** [comment]
@gaffneyc I made a PR implementing the case in the previous comment. Let me know if this would have worked for you and if you think it would be useful to have integrated into the library. Cheers

**Comment by gaffneyc** [comment]
@marioizquierdo Thanks for taking a stab at it though I'm not sure it would be useful to us right now (and sorry for not following up sooner) and, from our discussion, I'm not sure it would be a good fit for Twirp.

The pattern we've landed on is to write a basic wrapper client that made it easier to use domain objects and we were able to have the exception raising in that code. This mostly came out because we've found it annoying to translate between objects and protobuf types (UUIDs are especially annoying).

For example:
```ruby
class DMS::Dispatch::Client
  def get_snitch(snitch)
    request = ::DMS::Dispatch::RPC::GetSnitchRequest.new(id: uuid_to_binary(snitch.id))
    response = @client.get_snitch(request)
    check_error!(response)

    GetSnitchResponse.new(response)
  end
end
```

**Comment by marioizquierdo** [comment]
Excellent. I like your solution of making a client wrapper and using your own helper `check_error!(response)`, I assume from the name with `!` that it will raise an exception that is appropriate to your application.

Ok I'll close the PR #40 as well, but this issue and that PR will still work as reference for others that may have the same problem. It makes more sense to keep Twirp low level, focused on serialization, and then use your own client wrappers, or maybe in the future another higher level library on top of it, to get more domain-specific functionality.
